services:
  backend-service:
    build:
      context: ./backend
    container_name: backend-service
    ports:
      - "8080:8080"
    env_file:
      - ./backend/.env.prod
    depends_on:
      - database_service

  database_service:
    image: postgres:17-alpine
    container_name: xaqsoor_db
    restart: on-failure
    env_file:
      - ./backend/.env.prod
    ports:
      - "5462:5432"
    volumes:
      - xaqsoor_pgdata:/var/lib/postgresql/data

  client-app:
    build:
      context: ./frontend/client-app
      args:
        NEXT_PUBLIC_API_URL: https://app.xaqsoorparty.so/api
    container_name: client_app
    ports:
      - "3000:3000"
    depends_on:
      - backend-service

  admin-panel:
    build:
      context: ./frontend/admin-panel
      args:
        NEXT_PUBLIC_API_URL: https://app.xaqsoorparty.so/api
    container_name: admin_panel
    ports:
      - "3001:3001"
    depends_on:
      - backend-service

volumes:
  xaqsoor_pgdata:
