services:
  postgres:
    image: postgres:17-alpine
    container_name: authshield
    restart: on-failure
    environment:
      POSTGRES_DB: authshield_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5462:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data:
