spring:
  application:
    name: xaqsoor-membership-management
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: ${DB_DDL_STRATEGY:update}
    show-sql: ${SHOW_SQL:false}
    open-in-view: false

  mail:
    host: ${SMTP_HOST}
    port: ${SMTP_PORT}
    username: ${SMTP_USER}
    password: ${SMTP_PASSWORD}
    protocol: smtps
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: ${SMTP_SSL_TRUST}

  # File upload settings
  servlet:
    multipart:
      enabled: true
      max-file-size: ${MAX_FILE_SIZE:20MB}
      max-request-size: ${MAX_REQUEST_SIZE:20MB}

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET}

mail:
  verify:
    url: ${VERIFY_URL:http://localhost:3000/auth/}


ipInfo:
  api-token: ${IPINFO_TOKEN}

aws:
  region: ${AWS_REGION}
  accessKeyId: ${AWS_ACCESS_KEY}
  secretKey: ${AWS_SECRET_KEY}
  s3:
    bucket: ${S3_BUCKET}
