# Profiles
SPRING_PROFILES_ACTIVE: dev

# File upload limits
MAX_FILE_SIZE: 20MB
MAX_REQUEST_SIZE: 20MB

# Database
DB_HOST: localhost
DB_PORT: 5462
DB_NAME: xaqsoor_db
DB_USER: xqsr_pr0d_us3r_94f1
DB_PASSWORD: A&S*_6nC!N
DB_DDL_STRATEGY: validate
SHOW_SQL: true

# Email
SMTP_HOST: smtp.gmail.com
SMTP_PORT: 465
SMTP_USER: abdihakin18@gmail.com
SMTP_PASSWORD: bjoy oqpd sekw phma
SMTP_SSL_TRUST: smtp.gmail.com

# Security
JWT_SECRET: c7f803524217876a59ec1d6064779a60c58284a5db1ff96f28ec9d574c277fa79c62bead1a98ab48a1e5107abc99df46658b7e72289e516aaa2a30acae48ee55

# Mail verification URL
VERIFY_URL: http://localhost:3000/auth/

# IPInfo API token
IPINFO_TOKEN: 2a8f78eeac8331

# AWS
AWS_REGION: eu-north-1
AWS_ACCESS_KEY: AKIAXYKJWXY22ARGS437
AWS_SECRET_KEY: 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
S3_BUCKET: xaqsoor