# Profiles
SPRING_PROFILES_ACTIVE: prod

# File upload limits
MAX_FILE_SIZE: 20MB
MAX_REQUEST_SIZE: 20MB

# Database
DB_HOST: ${DB_HOST}
DB_PORT: ${DB_PORT}
DB_NAME: ${DB_NAME}
DB_USER: ${DB_USER}
DB_PASSWORD: ${DB_PASSWORD}
DB_DDL_STRATEGY: validate
SHOW_SQL: false

# Email
SMTP_HOST: ${SMTP_HOST}
SMTP_PORT: ${SMTP_PORT}
SMTP_USER: ${SMTP_USER}
SMTP_PASSWORD: ${SMTP_PASSWORD}
SMTP_SSL_TRUST: ${SMTP_SSL_TRUST}

# Security
JWT_SECRET: ${JWT_SECRET}

# Mail verification URL
VERIFY_URL: ${VERIFY_URL}

# IPInfo API token
IPINFO_TOKEN: ${IPINFO_TOKEN}

# AWS
AWS_REGION: ${AWS_REGION}
AWS_ACCESS_KEY: ${AWS_ACCESS_KEY}
AWS_SECRET_KEY: ${AWS_SECRET_KEY}
S3_BUCKET: ${S3_BUCKET}
